usgs/aqts-capture-ts-corrected

src/main/resources/application.yml

Title
-----------
Description
-----------

attempt to wrap resultObject

---

src/main/java/gov/usgs/wma/waterdata/ResultObject.java
src/main/resources/application.yml

Title
-----------
Description
-----------

Another attempt at correct json

---

src/main/java/gov/usgs/wma/waterdata/PreProcess.java
src/main/java/gov/usgs/wma/waterdata/ResultObject.java
src/test/java/gov/usgs/wma/waterdata/PreProcessIT.java
src/test/java/gov/usgs/wma/waterdata/PreProcessTest.java

Title
-----------
Description
-----------

try renaming property

---

code.json
pom.xml
serverless.yml
src/main/resources/sql/qualifiers.sql

Title
-----------
Description
-----------

end-of-sprint cleanup

---

pom.xml

Title
-----------
Description
-----------

boot 2.2.5

---

Jenkinsfile
package.json
serverless.yml

Title
-----------
Description
-----------

add resources for sns and cloudwatch alerts

---

Dockerfile
package.json
serverless.yml

Title
-----------
Description
-----------

use git commit as a tag

---

serverless.yml

Title
-----------
Description
-----------

increase timeout from 60 seconds to 90 seconds

---

src/main/java/gov/usgs/wma/waterdata/JsonDataDao.java

Title
-----------
Description
-----------

Eat exceptions for no routing

---

src/test/java/gov/usgs/wma/waterdata/JsonDataDaoIT.java

Title
-----------
Description
-----------

Temporary test inactivate

---

src/main/java/gov/usgs/wma/waterdata/JsonDataDao.java
src/test/java/gov/usgs/wma/waterdata/JsonDataDaoIT.java

Title
-----------
Description
-----------

Rollback last two commits

---

package.json
src/main/java/gov/usgs/wma/waterdata/PreProcess.java
src/main/java/gov/usgs/wma/waterdata/ResultObject.java
src/test/java/gov/usgs/wma/waterdata/PreProcessIT.java
src/test/java/gov/usgs/wma/waterdata/PreProcessTest.java

Title
-----------
Description
-----------

return a single timeseries object for further processing instead of list

---

Jenkinsfile

Title
-----------
Description
-----------

update Jenkinsfile for version and labels

---

Jenkinsfile

Title
-----------
Description
-----------

more adjustments to ci labels

---

.bumpversion.cfg
code.json
pom.xml

Title
-----------
Description
-----------

update minor version

---

Dockerfile
Jenkinsfile
package.json

Title
-----------
Description
-----------

Serverless update

---

serverless.yml
src/main/java/gov/usgs/wma/waterdata/PreProcess.java
src/test/java/gov/usgs/wma/waterdata/PreProcessTest.java

Title
-----------
Description
-----------

always include timeseries properties regardles of the value

---

.gitignore
Dockerfile
Jenkinsfile
package.json
pom.xml
serverless.yml

Bumped spring-cloud-function.version to 3.0.10.RELEASE
Dependabot request had a merge conflict.
Title
-----------
Description
-----------

IOW-651 Added support for deploying to DEV tier.

---

serverless.yml

Title
-----------
Description
-----------
Looks like this lambda consistently uses less than 256 mb.  Set to 384 to leave some leeway.

IOW-699 optimize memory usage for lambdas

---

package.json
serverless.yml

Title
-----------
https://internal.cida.usgs.gov/jira/browse/IOW-726
Description
-----------
* Added support for AWS elasticsearch logging

add support for elasticsearch logging

---

serverless.yml

Changed timeout to 10 seconds in serverless.yml
Title
-----------
Description
-----------

IOW-773 (Adjust aqts-capture lambda timeouts)

---

serverless.yml

Title
-----------
Description
-----------

IOW-781 add reserved concurrency

---

serverless.yml

Title
-----------
Description
-----------

changed tags

---

serverless.yml

This reverts commit f06920c4caa2891b1c14ef34772bb7c1ad2381ee.
Title
-----------
Description
-----------

Revert "IOW-733 (Adjust aqts-capture lambda timeouts)"

---

package.json
serverless.yml

Title
-----------
Description
-----------

IOW-776 use serverless-prune plugin

---

Dockerfile
Jenkinsfile

Title
-----------
Description
-----------

IOW-745 Stop using dockerhub image
